### PR TITLE
Added possibility to filter for version and fixed_in_version

### PR DESCRIPTION
**Pull request by pedwik**
Usage: Alias for fixed_in_version is "releaseversion", maybe not thought
that through. Anyhow, if a parameter "releaseversion = 2.7.1," (last
entry must be followed by a comma) then only records with
b.fixed_in_version = 2.7.1 are selected. If parameter "version" is used
instead, records with b.version are selected.
Example:
<matnis>
  releaseversion = 2.7.1,
</mantis>

<matnis>
  version = 2.7.1,
</mantis>

### CODE REVIEW

**Comment by tessus** [comment]
Thanks for the PR, but it has a few problems:

- the naming (as you mentioned) is not ok
- why does the last entry has to be followed by a comma? this is not very user friendly.
- it allows SQL injection

I'll use https://github.com/HSINWEI/mwExtensionMantis/commit/4ecbc7062da3d6d3e9e713e255630cba5a92c652 as a start and go from there. I'll have time this evening and look into it. The problem is not the coding, but writing the freaking documentation.

**Comment by pedwik** [comment]
Ok, the comma was not my intent, it should be fixed. Risk for SQL Injection
should be eliminated if we add a constraint that the first argument
character must be a number.

2017-09-06 19:38 GMT+02:00 Helmut K. C. Tessarek <notifications@github.com>:

**Comment by tessus** [comment]
I'll be off work in about 5 hours. I'll look into it then. But as I mentioned I will use this commit as a start -> https://github.com/HSINWEI/mwExtensionMantis/commit/4ecbc7062da3d6d3e9e713e255630cba5a92c652

I'm closing this PR. Please open a ticket 'support version and fixed_in_version'.

**Comment by pedwik** [comment]
An even more flexible filtering function for version number would allow
"less than" etc, but it is a bit work to do that in a sql query, although
doable.

2017-09-06 20:02 GMT+02:00 Helmut K. C. Tessarek <notifications@github.com>:

**Comment by tessus** [comment]
Hmm, think about this for a while. How would you do this, if you allowed a list of version numbers?
You have to find an additional logic that solves a bunch of problems. Translating into SQL is not the problem.

What do you do if you encounter 2 operators (not the value) that are the same e.g. `<`? What if expressions contradict each other? How to combine several operators (with AND or OR)? I would have to build an expression evaluator into the code, because I can't just send something to the database backend.

Unless you have an easy way to address these issues a flexible filter mechanism is out of the question.

**Comment by tessus** [comment]
Additional info: above examples are by far not the only cases that could occur.

**Comment by pedwik** [comment]
I do not think we have to overcomplicate things, but as a user I would appreciate defining a filter as for example

Version >= 2.71 for one wikitable, 

and Version < 2.7.1 for another.

The wiki extension is in my case only a tool to be able to show for example bug fixes to a broader group of users, users that have no access to the MantisBT.  I see no reason to implement a super-advanced parser for filtering versions. 

Mvh Peder

**Comment by tessus** [comment]
I've added new options (available on the master branch):

- `username`
- `fixed_in_version` alias: `fixed_in`
- `version`
- `target_version` alias: `target`

All of them allow a list of values (separated by comma)

Currently the `*version*` options cannot use operators like `<`, `>`, `<=`, `>=`

I have to think of a safe and easy way to handle these operators.

**Comment by pedwik** [comment]
Great Helmut! Concerning the operators, good old fortran-style operators
like gt, ge, eq, lt, le could be used maybe?

2017-09-07 3:54 GMT+02:00 Helmut K. C. Tessarek <notifications@github.com>:

**Comment by tessus** [comment]
@pedwik done. available in master. see commit message for explanation.

Now I have to release 2.0 and write the freaking documentation... Argh.

**Comment by tessus** [comment]
that's the commit https://github.com/tessus/mwExtensionMantis/commit/2553b0a6dfdc6edfaadbb4e6b00a5051d5ca0f9c

**Comment by tessus** [comment]
sorry, wrong commit. that's the right one: 820ccb3f9ab72d2c2a09dada4bd64644242a92ec

**Pull request closed without merging**
